# Generated by Django 5.2.17 on 2026-09-20 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgaoAmbiental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ServicoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_servico', models.CharField(max_length=150)),
                ('data_registro', models.DateField(auto_now_add=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=150)),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('contato_nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('usuario_vinculado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ADMIN', 'Administrador/Equipe'), ('CLIENTE', 'Cliente')], default='CLIENTE', max_length=10)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em Andamento'), ('PENDENTE', 'Pendente com Órgão'), ('CONCLUIDO', 'Concluído')], default='EM_ANDAMENTO', max_length=20)),
                ('data_inicio', models.DateField()),
                ('prazo_vencimento', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='core.cliente')),
                ('orgao_ambiental', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.orgaoambiental')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_responsaveis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ObservacaoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observacoes', to='core.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to='documentos_ambientais/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='ServicoLaudoTecnico',
            fields=[
                ('servicobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.servicobase')),
                ('area_estudo_hectares', models.DecimalField(decimal_places=2, max_digits=8, max_length=10)),
                ('art_numero', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.servicobase',),
        ),
        migrations.CreateModel(
            name='ServicoLicenciamento',
            fields=[
                ('servicobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.servicobase')),
                ('numero_licenca', models.CharField(max_length=50)),
                ('fase', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.servicobase',),
        ),
        migrations.AddField(
            model_name='servicobase',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='core.projeto'),
        ),
    ]
