# Generated by Django 5.2.17 on 2026-09-21 01:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgaoambiental',
            options={'verbose_name': 'Órgão Ambiental', 'verbose_name_plural': 'Órgãos Ambientais'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
        migrations.AlterModelOptions(
            name='servicobase',
            options={'verbose_name': 'Serviço Ambiental', 'verbose_name_plural': 'Serviços Ambientais'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='ddd',
            field=models.CharField(blank=True, default='11', help_text='Apenas 2 dígitos (Ex: 11)', max_length=2, validators=[django.core.validators.RegexValidator(message='Este campo aceita apenas números.', regex='^\\d+$')], verbose_name='Código de Área (DDD)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ddi',
            field=models.CharField(blank=True, default='55', help_text='Apenas números (Ex: 55)', max_length=3, validators=[django.core.validators.RegexValidator(message='Este campo aceita apenas números.', regex='^\\d+$')], verbose_name='Código do País (DDI)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone_numero',
            field=models.CharField(blank=True, default='000000000', help_text='Apenas números (até 9 dígitos)', max_length=10, validators=[django.core.validators.RegexValidator(message='Este campo aceita apenas números.', regex='^\\d+$')], verbose_name='Número do Telefone'),
        ),
    ]
